### ISSUE TITLE
Refresh not working as expected when using Jetbrains Gateway

### ISSUE THREAD

**Issue by delucca** [FirstTimeInForever/intellij-pdf-viewer#124]
Hi!

I'm using Jetbrains Gateway, and when I compile a new PDF file with TeXiFy and I open the PDF for some reason it doesn't refresh (even if I hit the refresh button).

If I open the file on the file explorer I can confirm that the source PDF file has changed.

Also, for some reason, the PDF view is extremely slow, and I need to install it both as a Host and Client plugin

Any thoughts?

**Comment by PHPirates** [comment]
That you need to install the plugin also on the client side sounds not unlikely, it may be the problems are similar to the Code With Me situation. I'm glad to hear you can at least see the pdf, I'll try to reproduce the refresh issue tomorrow. Is the new version shown if you close and reopen the pdf, or restart?

**Comment by PHPirates** [comment]
I can't reproduce the issue. I only installed TeXiFy and the PDF Viewer in the host, and refreshing works fine.
What are you connecting to? Linux server via ssh?
Can you try restarting the IDE backend on the host? When I just tried Gateway, it was super buggy and I needed like 5 restarts to get it working.
Also maybe try uninstalling the plugins from the client.

> the PDF view is extremely slow

What exactly is slow?

**Comment by PHPirates** [comment]
Thanks for commenting, if you also experience both the slow loading and refresh not working as in the original issue description then maybe they are related.
Are you sure that there is a stable and fast internet connection between the host and client?

Could you try to reproduce the issue with Markdown files, as those also use the JCEF preview, and the Asciidoc plugin with JCEF enabled? (https://intellij-asciidoc-plugin.ahus1.de/docs/users-guide/features/preview/jcef-preview.html#how-to-enable-the-jcef-preview)

Possibly some log files could be helpful: https://intellij-support.jetbrains.com/hc/en-us/articles/360016644459-Reporting-JCEF-problems

**Comment by PHPirates** [comment]
Please reopen if you have more information

**Comment by SanParraguez** [comment]
The connection should not be an issue. I have faced the issue both with a 'poor' connection and when connected at the same building to the server. Connecting in the same building, the "Backend Status Detail" tab of PyCharm shows a latency oscillating around 10ms, a CPU load of less than 5% at all times, and a memory usage of roughly 40% (at the moment). If I ping from my WSL terminal I get 1 ms on average with 0% packet loss (out of ~250).

I couldn't reproduce the issue with Markdown files, they all render at a rather normal speed without problems with and without the Asciidoc plugin enabled/installed.

I can load a small pdf created with Tikz (which is inserted in the main document), but it doesn't refresh automatically, only when I click the 'reload' button. If I wait long enough (about half a minute) it pops the message that the file has been changed on disk, and the reload button there also properly refreshes the file.

The log indeed showed some related errors.
[idea.log](https://github.com/user-attachments/files/19565806/idea.log)

**Comment by PHPirates** [comment]
Thanks, unfortunately I don't have any idea where the problem could be at the moment. If Markdown works fine it may not be a JCEF issue, but I don't know what else could affect the performance.

> If I wait long enough (about half a minute) it pops the message that the file has been changed on disk, and the reload button there also properly refreshes the file.

Sounds really interesting, I can't quite find anything in the documentation about this though. But this would suggest a possible issue with Gateway.


Thanks for the logs, I don't see any obvious errors, but could you also upload the logs from the host? See https://www.jetbrains.com/help/idea/remote-development-troubleshooting.html#logs_UI

```
2025-04-02 11:37:26,186 [ 452593]   WARN - #c.i.o.f.i.EditorComposite - Cannot focus editor (splitters=com.intellij.openapi.fileEditor.impl.EditorsSplitters[,299,0,2179x1330,layout=java.awt.BorderLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=9,maximumSize=,minimumSize=,preferredSize=], composite=EditorComposite(identityHashCode=427496479, file=RdProtocolFile: \home\wampo\project\out\main.pdf), reason=preferredFocusedComponent is null)

org.intellij.plugins.markdown.ui.preview.jcef.impl.LoadErrorException: Failed to load http://localhost:63345/markdownPreview/829924951/markdown-preview-index-925133423.html?_ijt=2vufmj9l9jpcqk37hj9iu9chgc:
ERR_ABORTED: ERR_ABORTED
	at org.intellij.plugins.markdown.ui.preview.jcef.impl.JcefUtilKt$waitForLoad$2$handler$1.onLoadError(JcefUtil.kt:64)
	at com.intellij.ui.jcef.JBCefClient$11.lambda$onLoadError$3(JBCefClient.java:553)
	at com.intellij.ui.jcef.JBCefClient$HandlerSupport.lambda$handleAll$0(JBCefClient.java:730)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2351)
	at com.intellij.ui.jcef.JBCefClient$HandlerSupport.handleAll(JBCefClient.java:730)
	at com.intellij.ui.jcef.JBCefClient$11.onLoadError(JBCefClient.java:552)
	at jcef/org.cef.CefClient.onLoadError(CefClient.java:922)

2025-04-02 11:32:49,329 [ 175736]   WARN - #c.j.r.f.FrontendFileEditorManager - Synchronously waiting for editor for RdProtocolFile: \home\wampo\project\out\main.pdf
```

**Comment by wyssj** [comment]
I have the same issue, especially interesting because even if you delete the pdf, recreate it and open it, it shows the old version. I use matplot.pyplot.

**Comment by wyssj** [comment]
**– Do you also have the slow loading of the PDF?**  
No.

---

**– Do you have the plugin installed on the host or the client? Try installing it on the host only.**  
I had it installed on both the host and the client. After uninstalling it, the remote connection restarted and PDF viewing stopped working. I then closed all other PyCharm instances, reconnected, and the PDF viewing worked again — the bug no longer occurred.  
However, the PDFs now load significantly slower (~4s compared to instant before).  

---

**– Could you upload the logs from the host?**  
Can I send them to you directly? It’s not a sensitive project, but I’d feel more comfortable not posting the logs publicly.

---

**– Does the issue happen with any PDF or just a specific one?**  
Any. I could reproduce it with the following minimal code:

```python
import matplotlib.pyplot as plt

# a, b = 123, 456
a, b = 0, 1
fig, ax = plt.subplots()
ax.axis("off")
ax.table(cellText=[[f"First: {a}"], [f"Second: {b}"]], loc="center")
fig.savefig("out.pdf")
```
The displayed pdf did not change when I changed the numbers and ran it again. Also when I deleted it and recreated it, it also showed the old numbers. I checked for the true pdf with Visual Studio and by downloading it.

Hope this helps.

**Comment by PHPirates** [comment]
You could send logs privately by (mis)using the 'report vulnerability' button here: https://github.com/Hannah-Sten/TeXiFy-IDEA/security/advisories or find my email at the top in [this commit](https://github.com/FirstTimeInForever/intellij-pdf-viewer/commit/c54d483d4ffaabdda665f2f804a214ce6ca3b3b8.patch)

>  I then closed all other PyCharm instances, reconnected, and the PDF viewing worked again — the bug no longer occurred.

Then I suspect that the _actual_ bug here is the 4 second loading. Installing the plugin on the client should not work at all, that it somehow seems to load (but then not update) is just creating confusion I think. Let's stick to installing it in the host only. Maybe the logs will show something.

We already know it's not network speed, but I still have no idea why it's not slow for me. 
What version of Gateway are you using? Maybe try 2025.2 EAP. And what IDE and version do you have on the host?
What version of the pdf viewer plugin?

**Comment by PHPirates** [comment]
Thanks for the logs. Can you confirm the logs (the latest one) are from when you installed the plugin in the host only? 

I see one crash right before you collect the logs, although interestingly it seems to be the first occurrence since you installed the plugin yesterday, so not sure if this is causing the slow loading.

```
2025-06-26 12:14:00,452 [ 559804]   INFO - #c.j.r.f.GuestFileEditorManager - Changing selected editor ClientId(value=...): old Editor: file:///redacted/test.py, new {DUMB_AWARE=true, FILE_KEY=file:///redacted/out.pdf, CLIENT_ID=ClientId(value=...), synchronizerby userData()=com.jetbrains.rdserver.fileEditors.BackendFileEditorSynchronizer@7c0bb32c}
2025-06-26 12:14:11,092 [ 570444]   WARN - #c.j.r.c.BackendCefBrowser - Not supported on backend: setFocus
2025-06-26 12:14:11,107 [ 570459] SEVERE - #c.i.o.p.Task - Should not be called on remdev host
java.lang.UnsupportedOperationException: Should not be called on remdev host
	at com.jetbrains.rdserver.lux.awt.peer.LuxRobotPeer.keyPress(LuxRobotPeer.kt:32)
	at java.desktop/java.awt.Robot.keyPress(Robot.java:393)
	at com.firsttimeinforever.intellij.pdf.viewer.ui.editor.presentation.PdfPresentationController.clickInBrowserWindow(PdfPresentationController.kt:62)
	at com.firsttimeinforever.intellij.pdf.viewer.ui.editor.presentation.PdfPresentationController.access$clickInBrowserWindow(PdfPresentationController.kt:15)
	at com.firsttimeinforever.intellij.pdf.viewer.ui.editor.presentation.PdfPresentationController$enter$1.run(PdfPresentationController.kt:26)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:491)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressSynchronously$10(CoreProgressManager.java:581)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:85)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:249)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:223)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:203)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:249)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:502)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:467)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:103)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:103)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:109)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:103)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:463)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2025-06-26 12:14:11,111 [ 570463] SEVERE - #c.i.o.p.Task - PyCharm 2024.3.6  Build #PY-243.26574.90
2025-06-26 12:14:11,111 [ 570463] SEVERE - #c.i.o.p.Task - JDK: 21.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2025-06-26 12:14:11,111 [ 570463] SEVERE - #c.i.o.p.Task - OS: Linux
2025-06-26 12:14:11,112 [ 570464] SEVERE - #c.i.o.p.Task - Plugin to blame: PDF Viewer version: 0.17.0
```

I can have a look if it gives any clue.

**Comment by wyssj** [comment]
The logs are from when I had the bug of the pdf not updating - so when it was installed on both. I can create some later for the long loading time.
