### ISSUE TITLE
Cannot load PDF when there is a # in the project directory name

### ISSUE THREAD

**Issue by jml96** [FirstTimeInForever/intellij-pdf-viewer#29]
Hi,
I installed your plugin in Pycharm (2021.1.2 RC) but all pdf documents open as a blank document.
My iOS is MacOS Big Sur 11.3.1.
Thank you.

**Comment by PHPirates** [comment]
Works fine for me with 0.11.1 in PyCharm 2021.1.1 on Linux, so maybe a Mac problem? @cl445

**Comment by cl445** [comment]
The description is a bit unspecific. @jml96 Did you got an empty PDF or is it just displayed empty inside Pycharm? Are you able to open your PDF with an external viewer? Could you provide an example?

**Comment by jml96** [comment]
Hi Claas,
It is displayed blank inside Pycharm. Example attached.
Thank you.

![example](https://user-images.githubusercontent.com/7725532/119644749-250afd80-be15-11eb-8eae-08001e14d643.png)

**Comment by cl445** [comment]
Is it also empty in a viewer outside of Pycharm?

**Comment by jml96** [comment]
I tried with different pdf files. They open normally in finder

**Comment by cl445** [comment]
I am sorry, I cannot reproduce the error. At my setup, the PDF files are loading without any problems. This does not mean that there is no bug, but we need more information.

**Comment by jml96** [comment]
Which information do you need from me to further investigate the issue?
Thank you.

**Comment by cl445** [comment]
At the moment you are the only one with the bug, i.e. it is not yet clear whether the bug could also be outside of Pycharm. For documentation, it would be helpful to know versions of Mac OS, Pycharm and the plugin. And if you don't have any more ideas yourself, then unfortunately the only thing to do is to wait.

**Comment by FirstTimeInForever** [comment]
I've tested the current plugin version (`0.11.1`) with both IDEA and PyCharm `2021.1.2-RC` and it works fine.

> Which information do you need from me to further investigate the issue?
> Thank you.

Have you edited your pdfs with Preview app (i. e. deleting pages)?
Can you provide any document that could be used to reproduce the issue?
Please, also attach full IDE version infomation in this format:
```
PyCharm 2021.1.2 RC (Professional Edition)
Build #PY-211.7442.13, built on May 20, 2021
Licensed to JetBrains Team

Runtime version: 11.0.11+9-b1341.57 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: com.firsttimeinforever.intellij.pdf.viewer.intellij-pdf-viewer (0.11.1)
```

**Comment by jml96** [comment]
I get the same problem with any pdf.
I send below a template pdf.
[sample.pdf](https://github.com/FirstTimeInForever/intellij-pdf-viewer/files/6548778/sample.pdf)

PyCharm 2021.1.2 RC (Professional Edition)
Build #PY-211.7442.13, built on May 20, 2021
Runtime version: 11.0.11+9-b1341.57 x86_64
VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3.1
GC: ParNew, ConcurrentMarkSweep
Memory: 4933M
Cores: 8
Non-Bundled Plugins: com.firsttimeinforever.intellij.pdf.viewer.intellij-pdf-viewer (0.11.1), R4Intellij (211.6693.5)

Thanks.

**Comment by FirstTimeInForever** [comment]
@jml96 Can you try an alpha build mentioned [here](https://github.com/FirstTimeInForever/intellij-pdf-viewer/issues/30#issuecomment-848267520)? It has different implementation of web-view, so it might help.

**Comment by jml96** [comment]
I tried it and I got a fatal error. I also sent a report to author.

com.intellij.diagnostic.PluginException:  [Plugin: com.firsttimeinforever.intellij.pdf.viewer.intellij-pdf-viewer]
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:250)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.convertStub(ActionManagerImpl.java:220)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.getActionImpl(ActionManagerImpl.java:551)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.preloadActions(ActionManagerImpl.java:1601)
	at com.intellij.openapi.actionSystem.impl.ActionPreloader.preload(ActionPreloader.java:14)
	at com.intellij.openapi.application.Preloader.lambda$preload$0(Preloader.java:84)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.application.Preloader.lambda$preload$1(Preloader.java:74)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.instantiate(ActionManagerImpl.java:240)
	... 23 more
Caused by: java.lang.NoClassDefFoundError: com/firsttimeinforever/intellij/pdf/viewer/model/HistoryNavigationDirection
	at com.firsttimeinforever.intellij.pdf.viewer.actions.navigation.PdfNavigateByHistoryAction$Forward.<init>(PdfNavigateByHistoryAction.kt:14)
	... 28 more
Caused by: java.lang.ClassNotFoundException: com.firsttimeinforever.intellij.pdf.viewer.model.HistoryNavigationDirection PluginClassLoader(plugin=PluginDescriptor(name=PDF Viewer, id=com.firsttimeinforever.intellij.pdf.viewer.intellij-pdf-viewer, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/PyCharm2021.1/plugins/plugin-0.12.0-alpha.1.jar, version=0.12.0-alpha.1, package=null), packagePrefix=null, instanceId=5, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:215)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 29 more

**Comment by PHPirates** [comment]
I'm also having a problem with blank documents, using 0.12.0-alpha.4 on Windows, IJ 2021.2 EAP, on any pdf. Interestingly, it's only blank in right split, I can see the document when I open it in left split. Pretty interesting, but I don't have the time to debug it now.
![image](https://user-images.githubusercontent.com/15669080/121310984-3d464680-c904-11eb-9673-8e0740bdcbdc.png)

**Comment by jml96** [comment]
I tried different splitting option in iOS and I see a blank file in all of them

**Comment by jml96** [comment]
Hi,
In the new alpha version 0.12.0-alpha.4. instead of a blank document like in the previous versions now I get the following message when I try to open a pdf in pycharm.

![Screenshot 2021-09-07 at 16 01 13](https://user-images.githubusercontent.com/7725532/132367475-2a84feb5-5636-4d82-92f5-9eafc15b84c0.png)

Does it help you to try to fix the issue?

Thank you.

**Comment by Cele3x** [comment]
I had the same problem. No PDF was displayed in my PyCharm built-in viewer. 
The problem I had was probably because my project folder started with a "#", so ".../path/to/project/#thesis/document.pdf".

**Comment by StevenRoodhorst** [comment]
Same error here, on version 0.14.0. The folder has an `&`.

**Comment by PHPirates** [comment]
I can confirm this is still an issue (project directory starting with a `#`)

**Comment by liudongmiao** [comment]
Please check the artifacts plugin https://github.com/FirstTimeInForever/intellij-pdf-viewer/pull/112/checks 

I have checked with name `pdftest - _ . ! ~ * ' ( ) ; ? : @ & = + $ , # [  ] ✨.pdf` on macOS.
