### ISSUE TITLE
Forward search after compilation only works the second time

### ISSUE THREAD

**Issue by PHPirates** [FirstTimeInForever/intellij-pdf-viewer#31]
As brought up implicitly in #30

TeXiFy 0.7.7-alpha.2, pdf viewer 0.12.0-alpha.1

Expected:
* Type `\newpage Page $n$` in LaTeX
* Compile
* Forward search is executed but focus (caret) should stay in LaTeX

Actual:
* Type `\newpage Page $n$` in LaTeX
* Compile
* Document reloads but stays at same position
* Focus is transferred to pdf
* Place caret back and compile second time
* Now forward search is executed, although the marker disappears immediately and focus is still transferred

@slideclimb will have a look, the behaviour seems to have changed since 0.11

**Comment by PHPirates** [comment]
Current behaviour seems to be that the forward search is executed and puts a marker in the pdf, which immediately disappears because the pdf is reloaded.

**Comment by PHPirates** [comment]
After #76, it seems that the above issue (forward search executed but the marker disappears) can still occur but much less frequently. Now, it is more common that the forward search will be executed fine, except the marker does not appear. However, sometimes it does appear.
A second manual forward search worked in all cases I tried it.

Also saw this exception once:
```
Uncaught Wu: Required value was null.
java.lang.Throwable: [LOGSEVERITY_ERROR][webpack://light-pdf-viewer/./application/viewer.js?:1]:
Uncaught Wu: Required value was null.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.firsttimeinforever.intellij.pdf.viewer.jcef.JcefUtils$createDefaultConsoleMessageListener$1.invoke(JcefUtils.kt:104)
	at com.firsttimeinforever.intellij.pdf.viewer.jcef.JcefUtils$createDefaultConsoleMessageListener$1.invoke(JcefUtils.kt:101)
	at com.firsttimeinforever.intellij.pdf.viewer.jcef.JcefUtils$addConsoleMessageListener$1.onConsoleMessage(JcefUtils.kt:89)
	at com.intellij.ui.jcef.JBCefClient$3.lambda$onConsoleMessage$4(JBCefClient.java:305)
	at com.intellij.ui.jcef.JBCefClient$HandlerSupport.lambda$handle$0(JBCefClient.java:726)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at java.base/java.util.Collections$SynchronizedCollection.forEach(Collections.java:2131)
	at com.intellij.ui.jcef.JBCefClient$HandlerSupport.handle(JBCefClient.java:726)
	at com.intellij.ui.jcef.JBCefClient$HandlerSupport.handleBoolean(JBCefClient.java:731)
	at com.intellij.ui.jcef.JBCefClient$3.onConsoleMessage(JBCefClient.java:304)
	at jcef/org.cef.CefClient.onConsoleMessage(CefClient.java:352)
```

**Comment by PHPirates** [comment]
I can still reproduce this issue:

Expected:

-     Type `\newpage Page $n$ <caret>` in LaTeX
-     Compile
-     Type `\newpage Page $n+1$ <caret>`
-     Forward search is executed and the text just typed has a marker

Actual:

-     Type `\newpage Page $n$ <caret>` in LaTeX
-     Compile
-     Type `\newpage Page $n+1$ <caret>`
-     Document reloads but stays at page n, sometimes with a marker. Sometimes it goes to page n+1, so this may be a race condition
-     Compile second time
-     Now forward search is executed and the text on page n+1 has a marker (sometimes it has not)
