### ISSUE TITLE
IDE frequently freezes and crashes when automatically reloading the ducoment on chagne

### ISSUE THREAD

**Issue by Him188** [FirstTimeInForever/intellij-pdf-viewer#74]
When combined with TeXiFy, IDE frequently freezes and crashes by compiling the Tex file and hence updating the PDF. It won't happen if I turn off "Reload document on change".

**Comment by PHPirates** [comment]
Please upload idea.log (Help > Show Log) and follow this process for the IDE freeze issue: https://github.com/Hannah-Sten/TeXiFy-IDEA/wiki/Contributing-to-TeXiFy#debugging-performance-issues

Also please provide OS and TeXiFy and PDF Viewer versions

**Comment by Him188** [comment]
Here is the crash report and the logs. The crash happened just after I compiled a LaTeX file (The output PDF was open). I did not use auto-reload.

IDEA 2023.1, TeXiFy 0.7.29, PDF Viewer 0.14.3.

[crash.txt](https://github.com/FirstTimeInForever/intellij-pdf-viewer/files/11375534/crash.txt)

[idea.log](https://github.com/FirstTimeInForever/intellij-pdf-viewer/files/11375539/idea.log)

**Comment by PHPirates** [comment]
Many thanks for the logs. I'm seeing other plugins appear in the logs however, in particular this one: https://github.com/b3er/idea-archive-browser/issues
Could you please disable all other plugins except TeXiFy and PDF Viewer and then see if the issue reoccurs?

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00000001085fc3e8, pid=84634, tid=50571
#
# JRE version: OpenJDK Runtime Environment JBR-17.0.6+10-829.5-jcef (17.0.6+10) (build 17.0.6+10-b829.5)
# Java VM: OpenJDK 64-Bit Server VM JBR-17.0.6+10-829.5-jcef (17.0.6+10-b829.5, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, bsd-aarch64)
# Problematic frame:
# V  [libjvm.dylib+0x1243e8]  AccessInternal::PostRuntimeDispatch<G1BarrierSet::AccessBarrier<548964ull, G1BarrierSet>, (AccessInternal::BarrierType)2, 548964ull>::oop_access_barrier(void*)+0x8
#
# No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# If you would like to submit a bug report, please visit:
#   https://youtrack.jetbrains.com/issues/JBR
#

---------------  S U M M A R Y ------------

(...)

Host: "MacBookPro18,2" arm64, 10 cores, 32G, Darwin 22.2.0, macOS 13.1 (22C65)
Time: Tue May  2 17:31:54 2023 BST elapsed time: 1647.228671 seconds (0d 0h 27m 27s)

---------------  T H R E A D  ---------------

Current thread (0x00000001400b3a00):  JavaThread "pool-5-thread-9" [_thread_in_vm, id=50571, stack(0x00000002c5278000,0x00000002c547b000)]

Stack: [0x00000002c5278000,0x00000002c547b000],  sp=0x00000002c5479ea0,  free space=2055k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
V  [libjvm.dylib+0x1243e8]  AccessInternal::PostRuntimeDispatch<G1BarrierSet::AccessBarrier<548964ull, G1BarrierSet>, (AccessInternal::BarrierType)2, 548964ull>::oop_access_barrier(void*)+0x8
V  [libjvm.dylib+0x4c9454]  jni_SetByteArrayRegion+0x134
C  [lib7-Zip-JBinding.dylib+0x2ce38]  JNIEnv_::SetByteArrayRegion(_jbyteArray*, int, int, signed char const*)+0x14
C  [lib7-Zip-JBinding.dylib+0x2cd5c]  CPPToJavaSequentialOutStream::Write(void const*, unsigned int, unsigned int*)+0x70
C  [lib7-Zip-JBinding.dylib+0x56504]  COutStreamWithCRC::Write(void const*, unsigned int, unsigned int*)+0x54
C  [lib7-Zip-JBinding.dylib+0x42324]  COutBuffer::FlushPart()+0x94
C  [lib7-Zip-JBinding.dylib+0x423ac]  COutBuffer::Flush()+0x28
C  [lib7-Zip-JBinding.dylib+0x423e0]  COutBuffer::FlushWithCheck()+0x10
C  [lib7-Zip-JBinding.dylib+0x72194]  CLzOutWindow::CopyBlock(unsigned int, unsigned int)+0xd4
C  [lib7-Zip-JBinding.dylib+0xb86d8]  NCompress::NDeflate::NDecoder::CCoder::CodeSpec(unsigned int)+0x27c
C  [lib7-Zip-JBinding.dylib+0xb8a58]  NCompress::NDeflate::NDecoder::CCoder::CodeReal(ISequentialOutStream*, unsigned long long const*, ICompressProgressInfo*)+0xbc
C  [lib7-Zip-JBinding.dylib+0xb8eac]  NCompress::NDeflate::NDecoder::CCoder::CodeResume(ISequentialOutStream*, unsigned long long const*, ICompressProgressInfo*)+0x48
C  [lib7-Zip-JBinding.dylib+0x48d38]  NArchive::NGz::CHandler::Extract(unsigned int const*, unsigned int, int, IArchiveExtractCallback*)+0x2b4
C  [lib7-Zip-JBinding.dylib+0x159e8]  Java_net_sf_sevenzipjbinding_impl_InArchiveImpl_nativeExtract+0x1cc
j  net.sf.sevenzipjbinding.impl.InArchiveImpl.nativeExtract([IZLnet/sf/sevenzipjbinding/IArchiveExtractCallback;)V+0
j  net.sf.sevenzipjbinding.impl.InArchiveImpl.extractSlow(ILnet/sf/sevenzipjbinding/ISequentialOutStream;)Lnet/sf/sevenzipjbinding/ExtractOperationResult;+23
j  net.sf.sevenzipjbinding.simple.impl.SimpleInArchiveItemImpl.extractSlow(Lnet/sf/sevenzipjbinding/ISequentialOutStream;)Lnet/sf/sevenzipjbinding/ExtractOperationResult;+12
j  com.github.b3er.idea.plugins.arc.browser.base.sevenzip.AsyncCircularByteBuffer$fill$1$1$1.invoke(Lnet/sf/sevenzipjbinding/IInStream;)V+23
j  com.github.b3er.idea.plugins.arc.browser.base.sevenzip.AsyncCircularByteBuffer$fill$1$1$1.invoke(Ljava/lang/Object;)Ljava/lang/Object;+5
j  com.github.b3er.idea.plugins.arc.browser.formats.sevenzip.SevenZipArchiveHolder.useStream(Lkotlin/jvm/functions/Function1;)Ljava/lang/Object;+29
j  com.github.b3er.idea.plugins.arc.browser.base.sevenzip.AsyncCircularByteBuffer.fill$lambda-1(Lcom/github/b3er/idea/plugins/arc/browser/base/sevenzip/AsyncCircularByteBuffer;Lcom/github/b3er/idea/plugins/arc/browser/formats/sevenzip/SevenZipArchiveHolder;Lnet/sf/sevenzipjbinding/simple/ISimpleInArchiveItem;)V+54
j  com.github.b3er.idea.plugins.arc.browser.base.sevenzip.AsyncCircularByteBuffer$$Lambda$5304+0x0000000302b0dd38.run()V+12
J 34699 c2 java.util.concurrent.Executors$RunnableAdapter.call()Ljava/lang/Object; java.base@17.0.6 (14 bytes) @ 0x000000011d912c10 [0x000000011d912bc0+0x0000000000000050]
J 111333 c1 java.util.concurrent.FutureTask.run()V java.base@17.0.6 (123 bytes) @ 0x0000000116ca7670 [0x0000000116ca6e80+0x00000000000007f0]
J 84879 c1 java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V java.base@17.0.6 (187 bytes) @ 0x00000001147215a4 [0x0000000114720c80+0x0000000000000924]
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5 java.base@17.0.6
J 109982 c1 java.lang.Thread.run()V java.base@17.0.6 (17 bytes) @ 0x000000010f005328 [0x000000010f0051c0+0x0000000000000168]
v  ~StubRoutines::call_stub
V  [libjvm.dylib+0x4583b0]  JavaCalls::call_helper(JavaValue*, methodHandle const&, JavaCallArguments*, JavaThread*)+0x38c
V  [libjvm.dylib+0x4573cc]  JavaCalls::call_virtual(JavaValue*, Klass*, Symbol*, Symbol*, JavaCallArguments*, JavaThread*)+0x11c
V  [libjvm.dylib+0x457498]  JavaCalls::call_virtual(JavaValue*, Handle, Klass*, Symbol*, Symbol*, JavaThread*)+0x64
V  [libjvm.dylib+0x50c1ec]  thread_entry(JavaThread*, JavaThread*)+0xc4
V  [libjvm.dylib+0x9861e4]  JavaThread::thread_main_inner()+0x150
V  [libjvm.dylib+0x98486c]  Thread::call_run()+0xe0
V  [libjvm.dylib+0x7aec3c]  thread_native_entry(Thread*)+0x158
C  [libsystem_pthread.dylib+0x706c]  _pthread_start+0x94

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  net.sf.sevenzipjbinding.impl.InArchiveImpl.nativeExtract([IZLnet/sf/sevenzipjbinding/IArchiveExtractCallback;)V+0
j  net.sf.sevenzipjbinding.impl.InArchiveImpl.extractSlow(ILnet/sf/sevenzipjbinding/ISequentialOutStream;)Lnet/sf/sevenzipjbinding/ExtractOperationResult;+23
j  net.sf.sevenzipjbinding.simple.impl.SimpleInArchiveItemImpl.extractSlow(Lnet/sf/sevenzipjbinding/ISequentialOutStream;)Lnet/sf/sevenzipjbinding/ExtractOperationResult;+12
j  com.github.b3er.idea.plugins.arc.browser.base.sevenzip.AsyncCircularByteBuffer$fill$1$1$1.invoke(Lnet/sf/sevenzipjbinding/IInStream;)V+23
j  com.github.b3er.idea.plugins.arc.browser.base.sevenzip.AsyncCircularByteBuffer$fill$1$1$1.invoke(Ljava/lang/Object;)Ljava/lang/Object;+5
j  com.github.b3er.idea.plugins.arc.browser.formats.sevenzip.SevenZipArchiveHolder.useStream(Lkotlin/jvm/functions/Function1;)Ljava/lang/Object;+29
j  com.github.b3er.idea.plugins.arc.browser.base.sevenzip.AsyncCircularByteBuffer.fill$lambda-1(Lcom/github/b3er/idea/plugins/arc/browser/base/sevenzip/AsyncCircularByteBuffer;Lcom/github/b3er/idea/plugins/arc/browser/formats/sevenzip/SevenZipArchiveHolder;Lnet/sf/sevenzipjbinding/simple/ISimpleInArchiveItem;)V+54
j  com.github.b3er.idea.plugins.arc.browser.base.sevenzip.AsyncCircularByteBuffer$$Lambda$5304+0x0000000302b0dd38.run()V+12
J 34699 c2 java.util.concurrent.Executors$RunnableAdapter.call()Ljava/lang/Object; java.base@17.0.6 (14 bytes) @ 0x000000011d912c10 [0x000000011d912bc0+0x0000000000000050]
J 111333 c1 java.util.concurrent.FutureTask.run()V java.base@17.0.6 (123 bytes) @ 0x0000000116ca7670 [0x0000000116ca6e80+0x00000000000007f0]
J 84879 c1 java.util.concurrent.ThreadPoolExecutor.runWorker(Ljava/util/concurrent/ThreadPoolExecutor$Worker;)V java.base@17.0.6 (187 bytes) @ 0x00000001147215a4 [0x0000000114720c80+0x0000000000000924]
j  java.util.concurrent.ThreadPoolExecutor$Worker.run()V+5 java.base@17.0.6
J 109982 c1 java.lang.Thread.run()V java.base@17.0.6 (17 bytes) @ 0x000000010f005328 [0x000000010f0051c0+0x0000000000000168]
v  ~StubRoutines::call_stub

siginfo: si_signo: 11 (SIGSEGV), si_code: 2 (SEGV_ACCERR), si_addr: 0x0000000000000000
```

I did find some other unrelated crash, which I'm putting here for the record:

```
2023-05-02 16:37:28,162 [4018671] SEVERE - #o.j.i.BuiltInServer - IntelliJ IDEA 2023.1  Build #IU-231.8109.175
2023-05-02 16:37:28,162 [4018671] SEVERE - #o.j.i.BuiltInServer - JDK: 17.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2023-05-02 16:37:28,162 [4018671] SEVERE - #o.j.i.BuiltInServer - OS: Mac OS X
2023-05-02 16:37:28,163 [4018672] SEVERE - #o.j.i.BuiltInServer - Plugin to blame: PDF Viewer version: 0.14.3
2023-05-02 16:37:28,163 [4018672]   INFO - #o.j.i.BuiltInServer - Channel will be closed due to error
2023-05-02 16:37:28,164 [4018673]   INFO - #com.firsttimeinforever.intellij.pdf.viewer.utility.PdfResourceLoader - Loading internal resource: /web-view/pdf.worker.js.map
2023-05-02 16:37:28,164 [4018673]   INFO - #o.j.i.BuiltInServer - Channel will be closed due to error
2023-05-02 16:37:28,165 [4018674]   INFO - #com.firsttimeinforever.intellij.pdf.viewer.utility.PdfResourceLoader - Loading internal resource: /web-view/pdf.worker.js.map
2023-05-02 16:37:28,165 [4018674]   INFO - #o.j.i.BuiltInServer - Channel will be closed due to error
2023-05-02 16:37:28,165 [4018674]   INFO - #com.firsttimeinforever.intellij.pdf.viewer.utility.PdfResourceLoader - Loading internal resource: /web-view/pdf.worker.js.map
2023-05-02 16:37:28,165 [4018674]   INFO - #o.j.i.BuiltInServer - Channel will be closed due to error
2023-05-02 16:37:28,166 [4018675]   INFO - #com.firsttimeinforever.intellij.pdf.viewer.utility.PdfResourceLoader - Loading internal resource: /web-view/pdf.worker.js.map
2023-05-02 16:37:28,166 [4018675] SEVERE - #c.i.o.e.i.ExtensionPointImpl - Could not load resource file: /web-view/pdf.worker.js.map
java.io.FileNotFoundException: Could not load resource file: /web-view/pdf.worker.js.map
	at com.firsttimeinforever.intellij.pdf.viewer.utility.PdfResourceLoader.loadFromRoot(PdfResourceLoader.kt:34)
	at com.firsttimeinforever.intellij.pdf.viewer.jcef.PdfStaticServer.sendInternalFile(PdfStaticServer.kt:82)
	at com.firsttimeinforever.intellij.pdf.viewer.jcef.PdfStaticServer.process(PdfStaticServer.kt:46)
	at org.jetbrains.io.DelegatingHttpRequestHandler.process$checkAndProcess(DelegatingHttpRequestHandler.kt:21)
	at org.jetbrains.io.DelegatingHttpRequestHandler.access$process$checkAndProcess(DelegatingHttpRequestHandler.kt:15)
	at org.jetbrains.io.DelegatingHttpRequestHandler$process$1.invoke(DelegatingHttpRequestHandler.kt:35)
	at org.jetbrains.io.DelegatingHttpRequestHandler$process$1.invoke(DelegatingHttpRequestHandler.kt:34)
	at org.jetbrains.io.DelegatingHttpRequestHandler.process$lambda$0(DelegatingHttpRequestHandler.kt:34)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.findFirstSafe$lambda$0(ExtensionProcessingHelper.kt:47)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.computeSafeIfAny(ExtensionProcessingHelper.kt:57)
	at com.intellij.openapi.extensions.impl.ExtensionProcessingHelper.findFirstSafe(ExtensionProcessingHelper.kt:47)
	at com.intellij.openapi.extensions.ExtensionPointName.findFirstSafe(ExtensionPointName.kt:53)
	at org.jetbrains.io.DelegatingHttpRequestHandler.process(DelegatingHttpRequestHandler.kt:34)
	at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.kt:15)
	at org.jetbrains.io.DelegatingHttpRequestHandlerBase.messageReceived(DelegatingHttpRequestHandlerBase.kt:11)
	at org.jetbrains.io.SimpleChannelInboundHandlerAdapter.channelRead0(SimpleChannelInboundHandlerAdapter.java:21)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.http.cors.CorsHandler.channelRead(CorsHandler.java:95)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at org.jetbrains.io.PortUnificationServerHandler.decode(PortUnificationServerHandler.java:128)
	at org.jetbrains.io.PortUnificationServerHandler.messageReceived(PortUnificationServerHandler.java:76)
	at org.jetbrains.io.Decoder.channelRead(Decoder.java:23)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Him188** [comment]
Indeed the [archive browser plugin](https://github.com/b3er/idea-archive-browser) might be to blame. Thank you for analysing the logs.
