### ISSUE TITLE
IDE internal error, reporting plugin exception

### ISSUE THREAD

**Issue by jhzgjhzg** [FirstTimeInForever/intellij-pdf-viewer#94]
build number: PY-241.14494.241
Plugin version: 0.15.0
what I do: using an build-in PDF viewer when writing Latex documents, then 21 errors reported
Error message: 
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'com.firsttimeinforever.intellij.pdf.viewer.actions.view.PdfDecreaseScaleAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.firsttimeinforever.intellij.pdf.viewer.intellij-pdf-viewer]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

```

**Comment by Liskie** [comment]
same here

**Comment by PHPirates** [comment]
Duplicate of #93
